server:
  port: 8085
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teste
    username: root
    password: 2468
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
